{% set version = '0.2.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-leafgl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/leafgl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/leafgl/leafgl_{{ version }}.tar.gz
  sha256: 29e83db299e441212d43079145460656f482d407e09c6b1d86305c799252898a

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-geojsonsf
    - r-htmltools
    - r-jsonify
    - r-leaflet
    - r-sf
  run:
    - r-base
    - r-geojsonsf
    - r-htmltools
    - r-jsonify
    - r-leaflet
    - r-sf

test:
  commands:
    - $R -e "library('leafgl')"           # [not win]
    - "\"%R%\" -e \"library('leafgl')\""  # [win]

about:
  home: https://github.com/r-spatial/leafgl, https://r-spatial.github.io/leafgl/
  license: MIT
  summary: Provides bindings to the 'Leaflet.glify' JavaScript library which extends the 'leaflet'
    JavaScript library to render large data in the browser using 'WebGl'.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
